name: Cypress testing

on: pull_request
env:
    IMAGE_TAG: ${{ github.sha }}
    IMAGE: docker.pkg.github.com/${{ github.repository }}/veilarbportefoljeflatefs
    PRINT_PAYLOAD: true

jobs:
    cypress-run:
        name: Cypress run
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: "!contains(github.event.pull_request.title, 'no_cypress')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  headless: true
                  start: npm start cypress:run
                  wait-on: http://localhost:3000
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
